#!/usr/bin/env bash
# create-k8s-secrets.sh — Create Kubernetes TLS secrets for Confluent Platform
#
# Creates the following secrets in the 'confluent' namespace:
#   kafka-tls             — TLS secret for Kafka brokers
#   kraftcontroller-tls   — TLS secret for KRaft controllers
#   ca-pair-sslcerts      — CA certificate secret (used by CFK for trust)
#   kafka-client-tls      — Client certificate secret (used by OMB)
#
# Usage:
#   ./confluent/mtls/create-k8s-secrets.sh
#
# Environment variables (all optional):
#   CERTS_DIR    — Path to certificates directory (default: <repo-root>/certs)
#   NAMESPACE    — Kubernetes namespace            (default: confluent)

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

CERTS_DIR="${CERTS_DIR:-${REPO_ROOT}/certs}"
NAMESPACE="${NAMESPACE:-confluent}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
error() { echo "[ERROR] $*" >&2; exit 1; }

command -v kubectl &>/dev/null || error "kubectl not found in PATH"

usage() {
  cat <<EOF
Usage: $(basename "$0")

Create Kubernetes TLS secrets for Confluent Platform (KRaft + Kafka brokers).

Environment variables:
  CERTS_DIR    Path to certificates directory  (default: <repo-root>/certs)
  NAMESPACE    Kubernetes namespace             (default: confluent)

Prerequisites:
  - K3D cluster running and kubectl context set to 'k3d-confluent-benchmark'
  - Certificates generated by: ./confluent/mtls/generate-certs.sh

EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage; exit 0
fi

# Validate cert files exist
for f in \
    "${CERTS_DIR}/ca/ca.crt" \
    "${CERTS_DIR}/broker/broker.crt" \
    "${CERTS_DIR}/broker/broker.key" \
    "${CERTS_DIR}/kraftcontroller/kraftcontroller.crt" \
    "${CERTS_DIR}/kraftcontroller/kraftcontroller.key" \
    "${CERTS_DIR}/client/client.crt" \
    "${CERTS_DIR}/client/client.key"; do
  [[ -f "${f}" ]] || error "Certificate file not found: ${f}. Run generate-certs.sh first."
done

# ---------------------------------------------------------------------------
# 1. Create namespace if not exists
# ---------------------------------------------------------------------------
info "Ensuring namespace '${NAMESPACE}' exists..."
kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

# ---------------------------------------------------------------------------
# Helper: apply_secret — delete and recreate a secret (idempotent)
# ---------------------------------------------------------------------------
apply_secret() {
  local name="$1"
  shift
  if kubectl get secret "${name}" -n "${NAMESPACE}" &>/dev/null; then
    info "Secret '${name}' already exists — deleting and recreating..."
    kubectl delete secret "${name}" -n "${NAMESPACE}"
  fi
  info "Creating secret '${name}'..."
  kubectl "$@" -n "${NAMESPACE}"
  info "  Secret '${name}' created."
}

# ---------------------------------------------------------------------------
# 2. Kafka broker TLS secret
# ---------------------------------------------------------------------------
apply_secret "kafka-tls" \
  create secret generic kafka-tls \
  --from-file=tls.crt="${CERTS_DIR}/broker/broker.crt" \
  --from-file=tls.key="${CERTS_DIR}/broker/broker.key" \
  --from-file=ca.crt="${CERTS_DIR}/ca/ca.crt"

# ---------------------------------------------------------------------------
# 3. KRaft controller TLS secret
# ---------------------------------------------------------------------------
apply_secret "kraftcontroller-tls" \
  create secret generic kraftcontroller-tls \
  --from-file=tls.crt="${CERTS_DIR}/kraftcontroller/kraftcontroller.crt" \
  --from-file=tls.key="${CERTS_DIR}/kraftcontroller/kraftcontroller.key" \
  --from-file=ca.crt="${CERTS_DIR}/ca/ca.crt"

# ---------------------------------------------------------------------------
# 4. CA secret (used by CFK for trust anchor)
# ---------------------------------------------------------------------------
apply_secret "ca-pair-sslcerts" \
  create secret tls ca-pair-sslcerts \
  --cert="${CERTS_DIR}/ca/ca.crt" \
  --key="${CERTS_DIR}/ca/ca.key"

# ---------------------------------------------------------------------------
# 5. Client certificate secret (for OMB)
# ---------------------------------------------------------------------------
apply_secret "kafka-client-tls" \
  create secret generic kafka-client-tls \
  --from-file=tls.crt="${CERTS_DIR}/client/client.crt" \
  --from-file=tls.key="${CERTS_DIR}/client/client.key" \
  --from-file=ca.crt="${CERTS_DIR}/ca/ca.crt"

# ---------------------------------------------------------------------------
# Print summary
# ---------------------------------------------------------------------------
cat <<EOF

[INFO]  ============================================================
[INFO]  Kubernetes secrets created in namespace '${NAMESPACE}':
[INFO]
[INFO]    kafka-tls           — Kafka broker TLS
[INFO]    kraftcontroller-tls — KRaft controller TLS
[INFO]    ca-pair-sslcerts    — CA certificate pair
[INFO]    kafka-client-tls    — OMB client TLS
[INFO]
[INFO]  Verify with:
[INFO]    kubectl get secrets -n ${NAMESPACE}
[INFO]
[INFO]  Next step:
[INFO]    kubectl apply -f confluent/confluent-platform.yaml
[INFO]  ============================================================

EOF
