# namespace.yaml — Kubernetes namespace for Confluent Platform components
apiVersion: v1
kind: Namespace
metadata:
  name: confluent
  labels:
    app.kubernetes.io/managed-by: Helm
    kubernetes.io/metadata.name: confluent
